#!/bin/bash
# Test email service configuration

echo "=========================================="
echo "Email Service Test Script"
echo "=========================================="

echo -e "\n1. Checking .env configuration..."
if grep -q "EMAIL_PROVIDER" /home/ljutzkanov/Documents/Projects/archon/.env; then
    echo "✓ Email configuration section found in .env"
    echo ""
    echo "To test email service, configure one of these providers in .env:"
    echo ""
    echo "Option 1: Resend (Recommended)"
    echo "  EMAIL_PROVIDER=resend"
    echo "  EMAIL_FROM=noreply@your-domain.com"
    echo "  EMAIL_FROM_NAME=Archon"
    echo "  RESEND_API_KEY=re_your_api_key_here"
    echo ""
    echo "Option 2: SendGrid"
    echo "  EMAIL_PROVIDER=sendgrid"
    echo "  EMAIL_FROM=noreply@your-domain.com"
    echo "  EMAIL_FROM_NAME=Archon"
    echo "  SENDGRID_API_KEY=SG.your_api_key_here"
    echo ""
    echo "Option 3: SMTP (Gmail, Outlook, etc.)"
    echo "  EMAIL_PROVIDER=smtp"
    echo "  EMAIL_FROM=your-email@gmail.com"
    echo "  EMAIL_FROM_NAME=Archon"
    echo "  SMTP_HOST=smtp.gmail.com"
    echo "  SMTP_PORT=587"
    echo "  SMTP_USERNAME=your-email@gmail.com"
    echo "  SMTP_PASSWORD=your-app-password"
    echo "  SMTP_USE_TLS=true"
else
    echo "✗ Email configuration not found in .env"
    echo "  Run the email service setup first"
    exit 1
fi

echo -e "\n2. Test Email Templates"
echo "Templates available:"
echo "  ✓ welcome_email() - New user registration"
echo "  ✓ password_reset_email() - Password reset request"
echo "  ✓ password_reset_success_email() - Password reset confirmation"
echo "  ✓ organization_invitation_email() - Org invitation"
echo "  ✓ email_verification_email() - Email verification"
echo "  ✓ test_email() - Service test"

echo -e "\n=========================================="
echo "Email Service Setup Complete!"
echo "=========================================="
echo ""
echo "Next steps:"
echo "1. Configure one of the email providers in .env"
echo "2. Rebuild Docker container: docker compose build archon-server"
echo "3. Restart services: docker restart archon-server"
echo "4. Test with password reset endpoint"
echo ""
